# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190826_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2019-08-27'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2019-08-27'),
        ),
    ]
